"""Application-wide configuration constants."""

from __future__ import annotations

import os
from pathlib import Path

APP_NAME = "Air Canvas"
WINDOW_NAME = APP_NAME
CAMERA_SCAN_START = 0
CAMERA_SCAN_END = 8
PREFER_EXTERNAL_CAMERA = True
DEFAULT_CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30
MIRROR_CAMERA = True
CAMERA_READ_FAILURE_LIMIT = 10
CAMERA_RECONNECT_ATTEMPTS = 3
CAMERA_RECONNECT_DELAY_SECONDS = 0.5
DEBUG_CAMERA_UI = False
CAMERA_VALIDATION_FRAMES = 5
CAMERA_WARMUP_SECONDS = 1.5
CAMERA_WARMUP_FRAME_LIMIT = 45
CAMERA_VALID_FRAME_REQUIREMENT = 3
CAMERA_MIN_MEAN_BRIGHTNESS = 0.8
CAMERA_MIN_FRAME_STDDEV = 0.8
CAMERA_MIN_FRAME_DIFFERENCE = 0.05
# Backward-compatible aliases for non-camera modules.
CAMERA_INDEX = DEFAULT_CAMERA_INDEX
FRAME_WIDTH = CAMERA_WIDTH
FRAME_HEIGHT = CAMERA_HEIGHT

# Premium interface and animation settings
ENABLE_GLOW = True
ENABLE_HAND_SKELETON = True
ENABLE_PARTICLES = True
ENABLE_FINGER_TRAIL = True
FULLSCREEN = False
WHITEBOARD_LIGHT_COLOR: tuple[int, int, int] = (245, 247, 250)
WHITEBOARD_DARK_COLOR: tuple[int, int, int] = (16, 20, 30)
DEFAULT_WHITEBOARD_THEME = "light"
UI_SCALE = 1.0
UI_REFERENCE_WIDTH = 1600
UI_REFERENCE_HEIGHT = 900
UI_SCALE_MIN = 0.75
UI_SCALE_MAX = 1.25
UI_SCALE_OVERRIDE = 1.0
CAMERA_DISPLAY_MODE = "cover"
CAMERA_ZOOM_DEFAULT = 1.0
CAMERA_ZOOM_MIN = 0.65
CAMERA_ZOOM_MAX = 2.5
CAMERA_ZOOM_STEP = 0.10
CAMERA_PAN_X_DEFAULT = 0.0
CAMERA_PAN_Y_DEFAULT = 0.0
SHOW_GESTURE_HELP = True
ANIMATION_SPEED = 1.0
MAX_PARTICLES = 42
MAX_FINGER_TRAIL = 14
GLOW_DOWNSCALE = 0.5
HEADER_HEIGHT = 76
STATUS_BAR_HEIGHT = 42
HELP_PANEL_WIDTH = 220
MAX_HISTORY_STATES = 30
VIEW_TRANSITION_SECONDS = 0.28

# Public editable UI settings.
enable_glow = ENABLE_GLOW
enable_hand_skeleton = ENABLE_HAND_SKELETON
enable_particles = ENABLE_PARTICLES
enable_finger_trail = ENABLE_FINGER_TRAIL
fullscreen = FULLSCREEN
whiteboard_background = WHITEBOARD_LIGHT_COLOR
ui_scale = UI_SCALE
animation_speed = ANIMATION_SPEED

ROOT_DIR = Path(__file__).resolve().parent.parent
DEFAULT_MODEL_PATH = ROOT_DIR / "models" / "hand_landmarker.task"
MODEL_PATH = Path(os.environ.get("AIR_CANVAS_MODEL", DEFAULT_MODEL_PATH)).expanduser()
OUTPUT_DIR = ROOT_DIR / "outputs"

MAX_HANDS = 2
PREFERRED_DRAWING_HAND = "Right"
ALLOW_HAND_ROLE_SWITCHING = True
ENABLE_SECONDARY_HAND_COMMANDS = True
ENABLE_TWO_HAND_CLEAR = True
ENABLE_HAND_SWIPE_HISTORY = True
SECONDARY_HAND_ACCENT = (255, 170, 70)
EFFECT_QUALITY = "high"
MAX_PARTICLES_PER_HAND = 60
MAX_TRAIL_POINTS_PER_HAND = 25
DEBUG_DUAL_HAND_TRACKING = False
DEBUG_DRAWING_SMOOTHING = False
DEBUG_DRAWING_PIPELINE = False
DEBUG_DRAW_ASSIST = False
DEBUG_SHAPE_RECOGNITION = False
DRAW_ASSIST_DEFAULT = "medium"
ASSIST_LOW_WINDOW = 3
ASSIST_MEDIUM_WINDOW = 6
ASSIST_HIGH_WINDOW = 10
AUTO_SHAPE_DEFAULT = True
SHAPE_CONFIDENCE_THRESHOLD = 0.78
SHAPE_PREVIEW_TIMEOUT_SECONDS = 3.0
CLEANUP_DEFAULT = "balanced"
ENABLE_AI_TRANSFORM = False
ENABLE_DESKTOP_ANNOTATION = True
DESKTOP_OVERLAY_ALWAYS_ON_TOP = True
DESKTOP_OVERLAY_CLICK_THROUGH_DEFAULT = False
DESKTOP_TOOLBAR_VISIBLE_DEFAULT = True
DESKTOP_CAMERA_PREVIEW_DEFAULT = True
DESKTOP_HISTORY_LIMIT = 40
DESKTOP_DEFAULT_TOOL = "pen"
DESKTOP_DEFAULT_COLOR = "red"
DESKTOP_PEN_WIDTH = 7
DESKTOP_ERASER_WIDTH = 35
DESKTOP_HIGHLIGHTER_WIDTH = 28
DESKTOP_HIGHLIGHTER_ALPHA = 0.30
DESKTOP_LASER_ENABLED = True
DESKTOP_CALIBRATION_REQUIRED = False
DESKTOP_PRIMARY_MONITOR_ONLY = False
DESKTOP_CURSOR_MIRROR_X = True
DESKTOP_CURSOR_SENSITIVITY_X = 1.0
DESKTOP_CURSOR_SENSITIVITY_Y = 1.0
DESKTOP_CURSOR_MARGIN_X = 0.03
DESKTOP_CURSOR_MARGIN_Y = 0.03
LASER_COLOR = (0, 0, 255)
LASER_RADIUS = 8
LASER_GLOW_RADIUS = 22
LASER_TRAIL_LENGTH = 18
LASER_TRAIL_LIFETIME_SECONDS = 0.45
DEBUG_GESTURES = False
SHOW_BASE_SKELETON = False
SHOW_TECHNICAL_LANDMARKS = False
DEBUG_HAND_EFFECTS = False
SHOW_HAND_DEBUG_GEOMETRY = False
SHOW_PALM_BASIS_VECTORS = False
SHOW_TRACKING_TRIANGLES = False
SHOW_ALL_FINGERTIP_MARKERS = False
SHOW_ACTIVE_FINGERTIP_MARKER = True
PASSIVE_FINGERTIP_MARKER_RADIUS = 2
ACTIVE_FINGERTIP_MARKER_RADIUS = 8
SHOW_HAND_ROLE_LABEL = True
SHOW_HAND_CONFIDENCE_LABEL = False
SHOW_GESTURE_LABEL = True
HAND_EFFECT_STYLE = "arcane_hologram"
PRIMARY_EFFECT_COLOR = (30, 175, 255)
SECONDARY_EFFECT_COLOR = (255, 220, 80)
PALM_RING_COUNT = 3
PALM_PRIMARY_RING_COUNT = 3
PALM_RING_LINE_THICKNESS = 1
PALM_RING_GLOW_STRENGTH = 0.35
PALM_RING_DETAIL_DENSITY = "low"
PALM_RING_OPACITY_OUTER = 0.45
PALM_RING_OPACITY_MIDDLE = 0.65
PALM_RING_OPACITY_INNER = 0.90
PALM_ORIENTATION_SMOOTHING = 0.22
PALM_SCALE_SMOOTHING = 0.20
GLOW_BLUR_KERNEL = 9
GLOW_ALPHA = 0.25
PRIMARY_HUD_LINE = (190, 220, 245)
PRIMARY_HUD_ACCENT = (40, 170, 255)
PRIMARY_HUD_CORE = (220, 245, 255)
SECONDARY_HUD_LINE = (245, 210, 165)
SECONDARY_HUD_ACCENT = (255, 145, 110)
SECONDARY_HUD_CORE = (255, 235, 220)
FX_DEGRADE_BELOW_FPS = 20
FX_RECOVER_ABOVE_FPS = 24
FX_RECOVERY_HOLD_SECONDS = 3.0
PALM_RING_BASE_RADIUS = 34
PALM_RING_ROTATION_SPEED = 42.0
ENABLE_PALM_CORE = True
ENABLE_ORBIT_PARTICLES = False
ENABLE_FIRE_TRAIL = True
ENABLE_WRIST_TRAIL = False
ENABLE_PINCH_BURST = True
ENABLE_HAND_CONNECTION_ARC = False
HAND_EFFECT_QUALITY = "high"
MAX_FIRE_PARTICLES = 90
MAX_ORBIT_PARTICLES = 8
MAX_SPARK_STREAKS = 12
MAX_ENERGY_TRAIL_POINTS = 35
MIN_HAND_DETECTION_CONFIDENCE = 0.55
MIN_HAND_PRESENCE_CONFIDENCE = 0.55
MIN_TRACKING_CONFIDENCE = 0.55

TOOLBAR_HEIGHT = 74
TOOLBAR_MARGIN = 90
TOOL_GAP = 6
PINCH_THRESHOLD = 0.055
OPEN_PALM_HOLD_SECONDS = 1.0
OPEN_PALM_RESET_SECONDS = 0.35
TOOL_SELECTION_COOLDOWN_SECONDS = 0.35
TOOLBAR_DWELL_SECONDS = 0.25
TOOLBAR_FAST_DWELL_SECONDS = 0.18
TOOLBAR_REENTRY_COOLDOWN_SECONDS = 0.15
TOOLBAR_PINCH_INSTANT_ACTIVATION = True
TOOLBAR_SAFE_INSET = 5
PINCH_START_THRESHOLD = 0.055
PINCH_RELEASE_THRESHOLD = 0.075
DEBUG_TOOLBAR_INTERACTION = False

DEFAULT_BRUSH_SIZE = 7
MIN_BRUSH_SIZE = 2
MAX_BRUSH_SIZE = 40
BRUSH_STEP = 2
ERASER_MULTIPLIER = 4
SMOOTHING_ALPHA = 0.38
SMOOTHING_METHOD = "one_euro"
MIN_CUTOFF = 1.0
BETA = 0.02
DERIVATIVE_CUTOFF = 1.0
MAX_ALLOWED_POINT_JUMP = 180
INTERPOLATION_SPACING = 3
STROKE_POINT_BUFFER_SIZE = 6
DRAW_START_CONFIRM_FRAMES = 2
DRAW_END_CONFIRM_FRAMES = 2
DRAW_MIN_TRACKING_CONFIDENCE = 0.55
DRAW_SMOOTHING_SLOW = 0.22
DRAW_SMOOTHING_FAST = 0.58
DRAW_FAST_SPEED_THRESHOLD = 850.0
BASE_MAX_POINT_JUMP = 90
FAST_MOVE_MAX_POINT_JUMP = 180
MIN_DRAW_DISTANCE = 2.0
INTERPOLATION_STEP_PIXELS = 3.0
MAX_DRAW_FRAME_GAP_SECONDS = 0.15

COLORS: dict[str, tuple[int, int, int]] = {
    "Red": (0, 0, 255),
    "Blue": (255, 80, 0),
    "Green": (0, 210, 70),
    "Yellow": (0, 230, 255),
    "White": (255, 255, 255),
}

MODEL_DOWNLOAD_URL = (
    "https://storage.googleapis.com/mediapipe-models/hand_landmarker/"
    "hand_landmarker/float16/latest/hand_landmarker.task"
)
